# Generated by Django 5.2.7 on 2025-11-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_organization', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('year_certified', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('skills', models.ManyToManyField(blank=True, related_name='certifications', to='projects.skill')),
            ],
            options={
                'ordering': ['-order', '-year_certified'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('skills', models.ManyToManyField(blank=True, related_name='education', to='projects.skill')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-order', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('skills', models.ManyToManyField(blank=True, related_name='experiences', to='projects.skill')),
            ],
            options={
                'ordering': ['-order', '-start_date'],
            },
        ),
    ]
